// Builds parts/optimity_body.html on the shared case study scaffolding.
const fs = require('fs');
const path = require('path');
const dir = path.join(__dirname, 'parts');
const ed = fs.readFileSync(path.join(dir, 'edabroad_body.html'), 'utf8');

const IMG = {
  cover: '/_blob/d06ba297ff82480a74763f9473568902',
  live: '/_blob/76e42fa0332b45286b6374724fcaa307',
  mobile: '/_blob/885720a5a3f8e6636f7aaf86711dc826',
  system: '/_blob/04c35f9d0b632658cf05ed9f7ad0530e',
  brand: '/_blob/6913b6efd3ab097263fc63f5bf3c9b3c',
  wire: '/_blob/59f5bca8e6e38f17a3a93013f841a535'
};

const baseCss = ed.slice(0, ed.indexOf('</style>'));
const nav = ed.slice(ed.indexOf('  <!-- ================= NAV ================= -->'), ed.indexOf('  </header>') + '  </header>'.length);
const script = ed.slice(ed.indexOf('<script type="text/x-dc"')).replace('"height":9800', '"height":8600');
if (!baseCss || !nav.includes('<nav') || !script.includes('initToc(root, reduced)')) throw new Error('scaffold missing');

const h2 = (n, label, title) => '          <p class="cs-idx">' + n + ' / ' + label + '</p>\n          <h2 class="cs-h2">' + title + '</h2>';
const p = (txt) => '          <p class="cs-p">' + txt + '</p>';
const fig = (src, alt, cap, cls) => [
  '          <figure class="cs-fig' + (cls ? ' ' + cls : '') + '" data-reveal>',
  '            <img src="' + src + '" alt="' + alt + '" loading="lazy">',
  cap ? '            <figcaption>' + cap + '</figcaption>' : '',
  '          </figure>'
].filter(Boolean).join('\n');
const toc = [
  ['client', 'The client'], ['goals', 'Goals'], ['team', 'The team'], ['brand', 'Brand guidelines'],
  ['wireframes', 'Wireframes'], ['system', 'Design system'], ['visual', 'Visual design'], ['build', 'Development'], ['results', 'Results']
];
const swatches = [['#355DEE', 'Primary blue'], ['#33D6C6', 'Teal'], ['#FFD333', 'Yellow'], ['#FD677C', 'Coral'], ['#33575F', 'Deep slate']];

const body = [
  '<div class="{{themeClass}}" style="background: var(--canvas); min-height: 100vh;">',
  '<div id="home-root" ref="{{setRoot}}" class="sheet" style="position: relative; box-sizing: border-box; background: var(--canvas); color: var(--ink); font-family: \'Space Grotesk\', sans-serif; overflow-x: clip;">',
  '',
  '  <div data-top-sentinel aria-hidden="true" style="position: absolute; top: 0; left: 0; width: 1px; height: 1px;"></div>',
  '',
  nav,
  '',
  '  <!-- ================= CASE STUDY HEADER ================= -->',
  '  <section class="pad" style="box-sizing: border-box; width: 100%; padding: 64px 80px 48px 80px;">',
  '    <div class="wrap">',
  '      <a class="fill-link" href="Work.dc.html" style="font-size: 14.5px; font-weight: 600; padding-bottom: 4px;"><svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M13 8H3"></path><path d="M7 4L3 8l4 4"></path></svg>All work</a>',
  '      <div class="cs-headrow">',
  '      <div class="cs-head" data-reveal>',
  '        <p class="lbl" style="margin: 0 0 18px 0;">Case study / Website design</p>',
  '        <h1 class="cs-title">Optimity</h1>',
  '        <p class="cs-lede">Driving B2B growth for a health, wellness, and insurance startup.</p>',
  '      </div>',
  '        <div class="cs-hstats" data-reveal data-d="1" aria-label="Results">',
  '          <div class="cs-hstat"><span class="n">55%</span><span class="t">bounce rate on the new website</span></div>',
  '          <div class="cs-hstat alt"><span class="n">15%</span><span class="t">lower than competitors, who sit at 70%</span></div>',
  '        </div>',
  '      </div>',
  '      <dl class="cs-meta" data-reveal data-d="1">',
  '        <div><dt>My role</dt><dd>UI designer</dd></div>',
  '        <div><dt>Delivered</dt><dd>4 pages, desktop and mobile</dd></div>',
  '        <div><dt>Built in</dt><dd>Webflow, with a development partner</dd></div>',
  '        <div><dt>Industry</dt><dd>Health, wellness and insurtech</dd></div>',
  '      </dl>',
  '    </div>',
  '  </section>',
  '',
  '  <section class="pad" style="box-sizing: border-box; width: 100%; padding: 0 80px 96px 80px;">',
  '    <div class="wrap">',
  '      <figure class="cs-cover" data-reveal><img src="' + IMG.cover + '" alt="Optimity website pages laid out at an angle: the homepage hero reading Optimize client engagement for a better experience, the Engage and grow your best clients page, and sections about health engagement built on the science of behavior change."></figure>',
  '      <p class="cs-intro" data-reveal>Discover how we created a visually captivating and user-friendly website that helped Optimity achieve a stronghold in the health, wellness &amp; insuretech industry driving B2B growth.</p>',
  '    </div>',
  '  </section>',
  '',
  '  <!-- ================= BODY: contents rail + chapters ================= -->',
  '  <section class="pad" style="box-sizing: border-box; width: 100%; padding: 0 80px 120px 80px;">',
  '    <div class="wrap cs-grid">',
  '      <nav class="cs-toc hide-sm" data-toc aria-label="On this page">',
  '        <p class="cap" style="margin: 0 0 14px 0;">On this page</p>',
  toc.map(([id, l]) => '        <a href="#' + id + '">' + l + '</a>').join('\n'),
  '      </nav>',
  '',
  '      <div class="cs-main">',
  '',
  '        <section id="client" class="cs-sec" data-reveal>',
  h2('01', 'About the client', 'Healthier, wealthier and longer, one lesson at a time.'),
  p('Optimity is a micro-learning app that helps millions of people live healthier, wealthier, and longer. If you\'re looking to improve your health and wellness, it\'s essential that you get the information you need, personalized to your specific lifestyle and habits. Optimity does just that by taking data from your wearables and combining it with information from your lifestyle, to provide actionable insights. As a result, this system can help improve your health and improve your quality of life.'),
  p('Our team was delighted to be given the opportunity to create a website that showcases Optimity\'s brand and value proposition, helping to bring in new B2B clients.'),
  '        </section>',
  '',
  '        <section id="goals" class="cs-sec" data-reveal>',
  h2('02', 'Project goals and requirements', 'Nail the brand, sell the USP, land B2B clients.'),
  p('We were tasked with creating a website that nails Optimity\'s branding, brings out its USP, and helps it land new B2B clients. Our primary objective was to collaborate with Optimity and contribute to their B2B growth by developing supplementary webpages. Throughout this project, we crafted an array of desktop and mobile webpages, that included:'),
  '          <div class="op-pages">',
  '            <div><span class="k">01</span><p>Homepage</p></div>',
  '            <div><span class="k">02</span><p>Enterprise Landing Page</p></div>',
  '            <div><span class="k">03</span><p>Health Grade Product Page</p></div>',
  '            <div><span class="k">04</span><p>Insurance Page</p></div>',
  '          </div>',
  p('Our overarching aim was to present Optimity\'s product offerings in a clear and compelling manner, emphasizing their potential advantages across various B2B sectors they were targeting. By effectively showcasing these benefits, we endeavored to enhance Optimity\'s market presence and facilitate their growth in the industry.'),
  '        </section>',
  '',
  '        <section id="team" class="cs-sec" data-reveal>',
  h2('03', 'Project team', 'Four people, one website.'),
  '          <ul class="op-team">',
  '            <li><span class="r">Design Lead</span><span class="n">Nivit Kochhar</span></li>',
  '            <li class="me"><span class="r">UI Designer</span><span class="n">Mahesh Reddy</span><span class="mg you">that\'s me</span></li>',
  '            <li><span class="r">Marketing &amp; Copy</span><span class="n">Julie Spugnardi</span></li>',
  '            <li><span class="r">Development</span><span class="n">Nikola Tripkovic</span></li>',
  '          </ul>',
  '        </section>',
  '',
  '        <section id="brand" class="cs-sec" data-reveal>',
  h2('04', 'Brand guidelines', 'Start from the brand they already had.'),
  p('Prior to initiating the design process, we conducted an extensive review of Optimity\'s established brand guidelines. Our objective was to ensure that our designs aligned seamlessly with their existing branding and overarching vision. By carefully studying these guidelines, we aimed to create designs that were in perfect harmony with Optimity\'s brand identity and effectively communicated their vision.'),
  '          <div class="op-swatches" aria-label="Optimity brand colours">',
  swatches.map(([hex, name]) => '            <div style="--c: ' + hex + ';"><span class="chip"></span><span class="hx">' + hex + '</span><span class="nm">' + name + '</span></div>').join('\n'),
  '          </div>',
  fig(IMG.brand, 'Brand colours and typography: Proxima Nova, with the palette #355DEE, #33D6C6, #FFD333, #FD677C and #33575F.', 'Proxima Nova and a five-colour palette, straight from Optimity\'s guidelines.'),
  '        </section>',
  '',
  '        <section id="wireframes" class="cs-sec" data-reveal>',
  h2('05', 'Wireframes and planning', 'Hierarchy first, colour later.'),
  p('During the Wireframing &amp; Planning stage, we initiated the process with initial sketches and wireframes for each webpage. Subsequently, we engaged in comprehensive discussions pertaining to information hierarchy and layout decisions.'),
  p('To give you a glimpse of this initial planning stage, we have included some visuals below.'),
  fig(IMG.wire, 'Greyscale desktop and mobile wireframes for the Optimity homepage, enterprise page and Health Grade page, showing hero sections, feature cards, statistics and testimonials.', 'Desktop and mobile wireframes for the homepage, enterprise and Health Grade pages.'),
  '        </section>',
  '',
  '        <section id="system" class="cs-sec" data-reveal>',
  h2('06', 'Design system', 'One set of parts for every page.'),
  p('As part of our project, we used the spark method, a comprehensive design system that we created specifically for this project. This involved developing a set of consistent design elements, such as typography, colour palettes, and button styles, that would be applied consistently across all webpages. By establishing a cohesive design system, we aimed to ensure visual harmony, improve user experience, and facilitate efficient collaboration throughout the project.'),
  p('This design system served as a foundation for maintaining brand consistency and providing a polished and cohesive UI for this next stage of Optimity\'s B2B web presence.'),
  fig(IMG.system, 'Optimity design system components: article and offer cards, primary and inverse buttons, a step counter card, a health quest progress card, heading and body type, the navigation bar and the footer.', 'Cards, buttons, stat modules, type, navigation and footer.'),
  '        </section>',
  '',
  '        <section id="visual" class="cs-sec" data-reveal>',
  h2('07', 'Visual design and mockups', 'From grey boxes to the finished look.'),
  p('During the mockups and visual design phase of the project, we transitioned from the conceptual stage to the creation of polished and visually captivating designs. Building upon the wireframes and design system, we meticulously crafted high-fidelity mockups that showcased the final look and feel of each webpage.'),
  p('Using our design system, we aimed to create visually compelling and engaging designs that aligned seamlessly with Optimity\'s brand identity. This phase allowed us to bring the project to life visually, ensuring that the end product would not only be visually appealing but also functional and user-friendly.'),
  fig(IMG.mobile, 'Mobile mockups of the Optimity Health Grade page: the hero, colourful step and stress stat bars, a phone showing a health grade of 80.4, and sections on segmentation and innovative health scoring.', 'Mobile mockups of the Health Grade product page.'),
  '        </section>',
  '',
  '        <section id="build" class="cs-sec" data-reveal>',
  h2('08', 'Development and guidelines', 'Built in Webflow, true to the file.'),
  p('During the development phase of the project, we established a valuable collaboration with Nikola, our trusted development partner who specializes in Webflow implementation. Working closely with Nikola, we seamlessly executed the implementation of the webpages.'),
  p('Leveraging their expertise and technical proficiency, Nikola played a pivotal role in transforming the design assets and specifications into a fully functional and visually stunning website.'),
  p('Below are some visuals of the live website in action.'),
  fig(IMG.live, 'The live Optimity homepage open on a laptop, with the headline Optimize client engagement for a better experience.', 'The live homepage.'),
  '        </section>',
  '',
  '        <section id="results" class="cs-sec" data-reveal>',
  h2('09', 'Results and concluding remarks', 'People stayed.'),
  '          <div class="op-bounce" aria-label="Bounce rate: Optimity 55 percent, competitors 70 percent">',
  '            <div class="row us"><span class="who">Optimity\'s new website</span><span class="bar"><i style="width: 55%;"></i></span><span class="v">55%</span></div>',
  '            <div class="row them"><span class="who">Competitors</span><span class="bar"><i style="width: 70%;"></i></span><span class="v">70%</span></div>',
  '            <p class="note">Bounce rate. Lower is better.</p>',
  '          </div>',
  p('We are proud to have played a role in enhancing Optimity\'s market presence and facilitating their growth in the industry. By crafting a website that effectively communicates Optimity\'s brand and value proposition, we have contributed to their mission of helping millions of people live healthier, wealthier, and longer lives.'),
  p('The results speak for themselves as Optimity\'s new website boasts an impressive bounce rate of 55%, a significant achievement that sets them apart from competitors in the market. This 15% lower bounce rate compared to their competitors\' rate of 70% showcases the website\'s effectiveness in retaining audience attention and fostering more interactions. We look forward to witnessing Optimity\'s continued success in the B2B sector and are grateful for the opportunity to have been part of their journey.'),
  '          <p class="mg rot cs-thanks">Thank you for reading! :)</p>',
  '        </section>',
  '',
  '      </div>',
  '    </div>',
  '  </section>',
  '',
  '  <!-- ================= NEXT ================= -->',
  '  <section class="pad" style="box-sizing: border-box; width: 100%; padding: 0 80px 120px 80px;">',
  '    <div class="wrap">',
  '      <a class="cs-more" href="EB5Resources.dc.html" data-cursor="next case study" data-reveal>',
  '        <span class="lbl">Up next</span>',
  '        <span class="t">EB5 Resources: a calm website for a big, expensive move</span>',
  '        <svg width="34" height="34" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 8h10"></path><path d="M9 4l4 4-4 4"></path></svg>',
  '      </a>',
  '    </div>',
  '  </section>',
  '',
  '  <!-- ================= CLOSING ================= -->',
  '  <footer class="pad" style="box-sizing: border-box; width: 100%; padding: 34px 80px 42px 80px;">',
  '    <div class="wrap"><p style="margin: 0; font-size: 14px; color: var(--ink-2);">© 2026 Mahesh Reddy Remala</p></div>',
  '  </footer>',
  '',
  '  <div class="grain" aria-hidden="true"></div>',
  '  <div class="curring" data-cursor-ring aria-hidden="true"><span class="cl" data-cursor-label></span></div>',
  '  <div class="curdot" data-cursor-dot aria-hidden="true"></div>',
  '',
  '</div>',
  '</div>',
  '</x-dc>',
  '',
  ''
].join('\n');

const css = [
  '',
  '/* ================= OPTIMITY ================= */',
  '.op-pages { display: grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap: 12px; margin: 8px 0 30px 0; }',
  '.op-pages div { display: flex; align-items: baseline; gap: 14px; padding: 20px 22px; border-radius: 16px; background: var(--raised); border: 1px solid var(--border); }',
  '.op-pages .k { font-family: ui-monospace, \'SF Mono\', Menlo, Consolas, monospace; font-size: 12.5px; color: var(--primary); }',
  '.op-pages p { margin: 0; font-family: \'Space Grotesk\', sans-serif; font-size: 19px; letter-spacing: -0.015em; color: var(--ink); font-weight: 700; }',
  '.op-team { margin: 0; padding: 0; list-style: none; border-top: 1px solid var(--border); }',
  '.op-team li { display: grid; grid-template-columns: 200px minmax(0,1fr) auto; align-items: baseline; gap: 16px; padding: 18px 12px; border-bottom: 1px solid var(--border); }',
  '.op-team .r { font-family: ui-monospace, \'SF Mono\', Menlo, Consolas, monospace; font-size: 12.5px; letter-spacing: .03em; color: var(--ink-3); }',
  '.op-team .n { font-family: \'Space Grotesk\', sans-serif; font-size: 21px; letter-spacing: -0.015em; color: var(--ink); font-weight: 700; }',
  '.op-team li.me { background: var(--p-lav); border-radius: 14px; border-bottom-color: transparent; }',
  '.op-team li.me .n { color: var(--primary); }',
  '.op-team .you { margin: 0; font-size: 20px; color: var(--terra); rotate: -3deg; }',
  '.op-swatches { display: grid; grid-template-columns: repeat(5, minmax(0,1fr)); gap: 10px; margin: 24px 0 0 0; }',
  '.op-swatches div { display: flex; flex-direction: column; gap: 4px; }',
  '.op-swatches .chip { display: block; height: 86px; border-radius: 14px; background: var(--c); margin-bottom: 8px; transition: transform .5s cubic-bezier(.34,1.56,.64,1); }',
  '.op-swatches div:hover .chip { transform: translateY(-6px) rotate(-2deg); }',
  '.op-swatches .hx { font-family: ui-monospace, \'SF Mono\', Menlo, Consolas, monospace; font-size: 13px; color: var(--ink); }',
  '.op-swatches .nm { font-size: 13.5px; color: var(--ink-3); }',
  '.op-bounce { display: flex; flex-direction: column; gap: 14px; margin: 6px 0 34px 0; padding: 28px 30px; border-radius: 22px; background: var(--raised); border: 1px solid var(--border); }',
  '.op-bounce .row { display: grid; grid-template-columns: 190px minmax(0,1fr) 64px; align-items: center; gap: 16px; }',
  '.op-bounce .who { font-size: 15.5px; color: var(--ink-2); }',
  '.op-bounce .bar { height: 14px; border-radius: 999px; background: var(--sunken); overflow: hidden; }',
  '.op-bounce .bar i { display: block; height: 100%; border-radius: 999px; }',
  '.op-bounce .us .bar i { background: var(--primary); }',
  '.op-bounce .them .bar i { background: var(--border-strong); }',
  '.op-bounce .v { font-family: \'Space Grotesk\', sans-serif; font-size: 30px; letter-spacing: -0.03em; font-weight: 700; text-align: right; }',
  '.op-bounce .us .v { color: var(--primary); }',
  '.op-bounce .them .v { color: var(--ink-3); }',
  '.op-bounce .note { margin: 4px 0 0 0; font-family: ui-monospace, \'SF Mono\', Menlo, Consolas, monospace; font-size: 12px; color: var(--ink-3); }',
  '@media (max-width: 700px) { .op-pages { grid-template-columns: minmax(0,1fr); } .op-team li { grid-template-columns: minmax(0,1fr) auto; } .op-team .r { grid-column: 1 / -1; } .op-swatches { grid-template-columns: repeat(3, minmax(0,1fr)); } .op-bounce .row { grid-template-columns: minmax(0,1fr) 56px; } .op-bounce .who { grid-column: 1 / -1; } }',
  '</style>',
  '</helmet>',
  ''
].join('\n');

fs.writeFileSync(path.join(dir, 'optimity_body.html'), baseCss + css + body + script);
console.log('optimity_body.html written');
